### ISSUE TITLE
Implement popup to be on mistakes only

### ISSUE THREAD

**Issue by PMark-est** [PMark-est/SoftwareProjectUT24#10]
Popups are rendered on every word no matter if it's correct or not.
The popup should only activate when grammar or spelling mistakes are clicked.
Related user stories : [#1 and #2](https://github.com/PMark-est/SoftwareProjectUT24/wiki/Functional-and-non%E2%80%90functional-requirements#must-have)
Related use case:  [UC1](https://github.com/PMark-est/SoftwareProjectUT24/wiki/Use-Cases#uc1-visualizing-error-annotations-on-text)
Priority: Crucial

Estimated time: 8h

**Comment by IljaSobolev** [comment]
Took 1h.
