### ISSUE TITLE
Add suggestion info to popup

### ISSUE THREAD

**Issue by PMark-est** [PMark-est/SoftwareProjectUT24#11]
Make the popup display suggested words
Related user story : [#5](https://github.com/PMark-est/SoftwareProjectUT24/wiki/Functional-and-non%E2%80%90functional-requirements#must-have)
Related use case:  [UC1](https://github.com/PMark-est/SoftwareProjectUT24/wiki/Use-Cases#uc1-visualizing-error-annotations-on-text)
Priority: Crucial

Estimated time: 20h

**Comment by IljaSobolev** [comment]
Took 5h.
