### ISSUE TITLE
Highlighted words design

### ISSUE THREAD

**Issue by PMark-est** [PMark-est/SoftwareProjectUT24#12]
Design how highlighted words should look like.
Related user stories : [#3 and #4](https://github.com/PMark-est/SoftwareProjectUT24/wiki/Functional-and-non%E2%80%90functional-requirements#must-have)
Related use case:  [UC1](https://github.com/PMark-est/SoftwareProjectUT24/wiki/Use-Cases#uc1-visualizing-error-annotations-on-text)
Priority: High

Estimated time: 10h

**Comment by tonyNeStark** [comment]
<img width="973" alt="Screenshot 2024-10-19 at 18 47 09" src="https://github.com/user-attachments/assets/c8cf574a-ddbf-4c36-9ec6-5eb96cf4e70b">

green for positive comments
yellow for spelling mistakes
red for comments on grammar mistakes

7h
