### ISSUE TITLE
Popup logic

### ISSUE THREAD

**Issue by PMark-est** [PMark-est/SoftwareProjectUT24#13]
Design how the popups should be rendered. Meaning all popups at once, only the clicked word, when clicked on sentence, etc...
Related user stories : [#1 and #2](https://github.com/PMark-est/SoftwareProjectUT24/wiki/Functional-and-non%E2%80%90functional-requirements#must-have)
Related use case:  [UC1](https://github.com/PMark-est/SoftwareProjectUT24/wiki/Use-Cases#uc1-visualizing-error-annotations-on-text)
Priority: High

Estimated time: 10h

**Comment by tonyNeStark** [comment]
12h
<img width="1077" alt="Screenshot 2024-10-20 at 16 51 36" src="https://github.com/user-attachments/assets/7bf26581-c0af-4d64-a9cd-88465182a9ba">
<img width="1075" alt="Screenshot 2024-10-20 at 16 51 43" src="https://github.com/user-attachments/assets/e7cf8dc6-e498-4df7-ab52-53c7abb46401">
