### ISSUE TITLE
Design filtering system

### ISSUE THREAD

**Issue by PMark-est** [PMark-est/SoftwareProjectUT24#14]
Design what the system should look and act for filtering sentences based on suggested word types and mistake type (being grammatical or spelling)
Related user story : [#9](https://github.com/PMark-est/SoftwareProjectUT24/wiki/Functional-and-non%E2%80%90functional-requirements#must-have-1)
Related use case:  [UC2](https://github.com/PMark-est/SoftwareProjectUT24/wiki/Use-Cases#uc2-filtering-error-annotations-by-category)
Priority: High

Estimated time: 20h

**Comment by tonyNeStark** [comment]
17h
