### ISSUE TITLE
Extended search dropdown menu

### ISSUE THREAD

**Issue by PMark-est** [PMark-est/SoftwareProjectUT24#23]
In the extended search view, there should be a dropdown list that shows all the types available for the given attribute that is to be searched for.
Priority: High
Estimated time: 30h
See user story [#7](https://github.com/PMark-est/SoftwareProjectUT24/wiki/Functional-and-non%E2%80%90functional-requirements#search-and-filtering)
Deadline: 5th November

**Comment by tonyNeStark** [comment]
20h

**Comment by tonyNeStark** [comment]
+5h
