### ISSUE TITLE
Highlight based on error type

### ISSUE THREAD

**Issue by PMark-est** [PMark-est/SoftwareProjectUT24#24]
Grammatically incorrect words have different error types. Make it so each type of error has a different colour.
Priority: Medium
Estimated time: 15h
See user story [#18](https://github.com/PMark-est/SoftwareProjectUT24/wiki/Functional-and-non%E2%80%90functional-requirements#error-analysis-and-presentation)
Deadline: 1st November

**Comment by nisdar** [comment]
Took 15h
