### ISSUE TITLE
Design what the popup should look like

### ISSUE THREAD

**Issue by PMark-est** [PMark-est/SoftwareProjectUT24#6]
When the user has clicked on a word a popup appears over that word displaying suggested words
Design what that popup should look like

Related user stories : [#1 and #2](https://github.com/PMark-est/SoftwareProjectUT24/wiki/Functional-and-non%E2%80%90functional-requirements#must-have)
Related use case:  [UC1](https://github.com/PMark-est/SoftwareProjectUT24/wiki/Use-Cases#uc1-visualizing-error-annotations-on-text)
Priority: High

Estimated time: 10 hours

**Comment by tonyNeStark** [comment]
<img width="644" alt="Screenshot 2024-10-19 at 18 31 03" src="https://github.com/user-attachments/assets/27c6e96f-9242-4477-b7c5-c5b10383f861">
<img width="963" alt="Screenshot 2024-10-19 at 18 35 50" src="https://github.com/user-attachments/assets/24c6dc11-7f2e-4ea5-92d2-c20873cd393c">


time 10h
