### ISSUE TITLE
Implement pop up on random word

### ISSUE THREAD

**Issue by PMark-est** [PMark-est/SoftwareProjectUT24#7]
When the user clicks on a random word a popup should appear above it.
Initially we want to get it working in the first place, then we can worry about rendering it on the grammar mistakes.
Related user story : [#1](https://github.com/PMark-est/SoftwareProjectUT24/wiki/Functional-and-non%E2%80%90functional-requirements#must-have)
Related use case:  [UC1](https://github.com/PMark-est/SoftwareProjectUT24/wiki/Use-Cases#uc1-visualizing-error-annotations-on-text)
Priority: Crucial

Estimated time: 20h

**Comment by IljaSobolev** [comment]
Took 25h.
